//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:2.0.50727.42
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM.Client.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIGEM.Client.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		internal static System.Drawing.Bitmap NaveNodriza_Icon {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap NaveNodriza_SIU_Crear_NaveNodriza {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_SIU_Crear_NaveNodriza", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap NaveNodriza_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap NaveNodriza_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap NaveNodriza_PIU_PIU_NaveNodriza {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_PIU_PIU_NaveNodriza", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap NaveNodriza_IIU__Auto_ {
			get {
				object obj = ResourceManager.GetObject("NaveNodriza_IIU__Auto_", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Aeronave_Icon {
			get {
				object obj = ResourceManager.GetObject("Aeronave_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Aeronave_SIU_Crear_Aeronave {
			get {
				object obj = ResourceManager.GetObject("Aeronave_SIU_Crear_Aeronave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Aeronave_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("Aeronave_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Aeronave_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("Aeronave_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Aeronave_PIU_PIU_Aeronave {
			get {
				object obj = ResourceManager.GetObject("Aeronave_PIU_PIU_Aeronave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Aeronave_IIU__Auto_ {
			get {
				object obj = ResourceManager.GetObject("Aeronave_IIU__Auto_", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Pasajero_Icon {
			get {
				object obj = ResourceManager.GetObject("Pasajero_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Pasajero_SIU_SIU_create_instance {
			get {
				object obj = ResourceManager.GetObject("Pasajero_SIU_SIU_create_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Pasajero_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("Pasajero_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Pasajero_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("Pasajero_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Pasajero_PIU_PIU_Pasajero {
			get {
				object obj = ResourceManager.GetObject("Pasajero_PIU_PIU_Pasajero", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Pasajero_IIU__Auto_ {
			get {
				object obj = ResourceManager.GetObject("Pasajero_IIU__Auto_", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap PasajeroAeronave_Icon {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap PasajeroAeronave_SIU_SIU_create_instance {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_SIU_SIU_create_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap PasajeroAeronave_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap PasajeroAeronave_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap PasajeroAeronave_IIU_IIU_PasajeroAeronave {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_IIU_IIU_PasajeroAeronave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap PasajeroAeronave_PIU_PIU_PasajeroAeronave {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_PIU_PIU_PasajeroAeronave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap PasajeroAeronave_MDIU_MDIU_PasajeroAeronave {
			get {
				object obj = ResourceManager.GetObject("PasajeroAeronave_MDIU_MDIU_PasajeroAeronave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Revision_Icon {
			get {
				object obj = ResourceManager.GetObject("Revision_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Revision_SIU_SIU_create_instance {
			get {
				object obj = ResourceManager.GetObject("Revision_SIU_SIU_create_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Revision_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("Revision_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Revision_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("Revision_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap Revision_IIU_IIU_Revision {
			get {
				object obj = ResourceManager.GetObject("Revision_IIU_IIU_Revision", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Revision_PIU__Auto_ {
			get {
				object obj = ResourceManager.GetObject("Revision_PIU__Auto_", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap RevisionPasajero_Icon {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap RevisionPasajero_SIU_SIU_create_instance {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_SIU_SIU_create_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap RevisionPasajero_SIU_SIU_delete_instance {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_SIU_SIU_delete_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap RevisionPasajero_SIU_SIU_edit_instance {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_SIU_SIU_edit_instance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap RevisionPasajero_PIU_PIU_RevisionPasajero {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_PIU_PIU_RevisionPasajero", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap RevisionPasajero_IIU__Auto_ {
			get {
				object obj = ResourceManager.GetObject("RevisionPasajero_IIU__Auto_", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Administrador_Icon {
			get {
				object obj = ResourceManager.GetObject("Administrador_Icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	
		internal static System.Drawing.Bitmap agent {
			get {
				object obj = ResourceManager.GetObject("agent", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap apply {
			get {
				object obj = ResourceManager.GetObject("apply", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap blob {
			get {
				object obj = ResourceManager.GetObject("blob", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap cascade {
			get {
				object obj = ResourceManager.GetObject("cascade", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap changePassword {
			get {
				object obj = ResourceManager.GetObject("changePassword", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap close {
			get {
				object obj = ResourceManager.GetObject("close", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap closeAll {
			get {
				object obj = ResourceManager.GetObject("closeAll", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap down {
			get {
				object obj = ResourceManager.GetObject("down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap newicon {
			get {
				object obj = ResourceManager.GetObject("newicon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap edit {
			get {
				object obj = ResourceManager.GetObject("edit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		internal static System.Drawing.Bitmap delete {
			get {
				object obj = ResourceManager.GetObject("delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
				
		internal static System.Drawing.Bitmap enlarge
		{
			get
			{
				object obj = ResourceManager.GetObject("enlarge", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap error {
			get {
				object obj = ResourceManager.GetObject("error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exeNext {
			get {
				object obj = ResourceManager.GetObject("exeNext", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exePrevious {
			get {
				object obj = ResourceManager.GetObject("exePrevious", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exit {
			get {
				object obj = ResourceManager.GetObject("exit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exportToExcel {
			get {
				object obj = ResourceManager.GetObject("exportToExcel", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exportToWord {
			get {
				object obj = ResourceManager.GetObject("exportToWord", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap help {
			get {
				object obj = ResourceManager.GetObject("help", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap login {
			get {
				object obj = ResourceManager.GetObject("login", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap loginMenu {
			get {
				object obj = ResourceManager.GetObject("loginMenu", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap maximize {
			get {
				object obj = ResourceManager.GetObject("maximize", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap minimize {
			get {
				object obj = ResourceManager.GetObject("minimize", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap next {
			get {
				object obj = ResourceManager.GetObject("next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap preferences {
			get {
				object obj = ResourceManager.GetObject("preferences", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap previous {
			get {
				object obj = ResourceManager.GetObject("previous", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap print {
			get {
				object obj = ResourceManager.GetObject("print", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap refresh {
			get {
				object obj = ResourceManager.GetObject("refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap savePosition {
			get {
				object obj = ResourceManager.GetObject("savePosition", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap saveWidth {
			get {
				object obj = ResourceManager.GetObject("saveWidth", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap search {
			get {
				object obj = ResourceManager.GetObject("search", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap searchFilter {
			get {
				object obj = ResourceManager.GetObject("searchFilter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}		
		
		internal static System.Drawing.Bitmap splashImage {
			get {
				object obj = ResourceManager.GetObject("splashImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileHorizontal {
			get {
				object obj = ResourceManager.GetObject("tileHorizontal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileVertical {
			get {
				object obj = ResourceManager.GetObject("tileVertical", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap unknown {
			get {
				object obj = ResourceManager.GetObject("unknown", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap up {
			get {
				object obj = ResourceManager.GetObject("up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap warning {
			get {
				object obj = ResourceManager.GetObject("warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap nodenextblock {
			get {
				object obj = ResourceManager.GetObject("nodenextblock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap line {
			get {
				object obj = ResourceManager.GetObject("line", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
